---
spring:
  cloud:
    kubernetes:
      client:
        namespace: ''
  application:
    name: zuul

management:
  context-path: /status
  security:
    enabled: false

endpoints:
  enabled: false
  info:
    enabled: true
  routes:
    enabled: true

zuul:
  ignored-services: docker-registry, kubernetes, router, zuul